name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v2

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: dependenciesのインストール
        run: npm install

      - name: lintチェック
        run: npm run check

      - name: Build project
        run: npm run build
